trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: sudo mkdir -p /home/site/wwwroot/wp-content/themes/customtheme
    displayName: 'Create Theme Directory'

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'ftps://waws-prod-ch1-043.ftp.azurewebsites.windows.net/site/wwwroot'
      username: 'wordpresstest\$wordpresstest'
      password: 'yS6aKJjsQRZT4TkcRRlapAxWff3e2pduE6niufQ1wD5sWBGlab6mL8owjkfT'
      rootDirectory: 'wp-content/themes/customtheme'
      filePatterns: '**'
      remoteDirectory: '/site/wwwroot/wp-content/themes/customtheme'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false
    displayName: 'Upload Theme via FTP'
